language: sh
sudo: false
dist: bionic

addons:
  apt:
    update: true
    packages:
    - libpocl2
    - pocl-opencl-icd
    - ocl-icd-opencl-dev
    - gnat
    - gprbuild

install:
  - rm -rf ext
  - git clone https://github.com/flyx/OpenCLAda.git ext/OpenCLAda

script:
  - ./build.sh test
  - ./bin/qcolor -g test
  - ./bin/qcolor -c test 3

after_success:
  - bash <(curl -s https://codecov.io/bash)
